--KSY--
CREATE TABLE HOSPITAL(
    HOS_NUM NUMBER NOT NULL,	-- 일련번호
	HOS_ADDR VARCHAR2(200),		-- 주소
	HOS_DIV VARCHAR2(1),		-- 병원분류
	HOS_DIVNAME VARCHAR2(100),	-- 병원분류명
	HOS_EMCLS VARCHAR2(4),		-- 응급의료기관코드
	HOS_EMCLSNAME VARCHAR2(50),	-- 응급의료기관코드명
	HOS_ERYN VARCHAR2(1),		-- 응급실운영여부(1/2)
	HOS_ETC VARCHAR2(1500),		-- 비고
	HOS_MAPIMG VARCHAR2(300),	-- 간이약도
	HOS_NAME VARCHAR2(100),   	-- 기관명
	HOS_TELL1 VARCHAR2(20),   	-- 대표전화
	HOS_TELL3 VARCHAR2(20),   	-- 응급실전화
	HOS_TIME1C VARCHAR2(10),   	-- 진료종료시간(월요일)
	HOS_TIME2C VARCHAR2(10),   	-- 진료종료시간(화요일)
	HOS_TIME3C VARCHAR2(10),   	-- 진료종료시간(수요일)
	HOS_TIME4C VARCHAR2(10),   	-- 진료종료시간(목요일)
	HOS_TIME5C VARCHAR2(10),   	-- 진료종료시간(금요일)
	HOS_TIME6C VARCHAR2(10),   	-- 진료종료시간(토요일)
	HOS_TIME7C VARCHAR2(10),   	-- 진료종료시간(일요일)
	HOS_TIME8C VARCHAR2(10),   	-- 진료종료시간(공휴일)
	HOS_TIME1S VARCHAR2(10),   	-- 진료시작시간(월요일)
	HOS_TIME2S VARCHAR2(10),   	-- 진료시작시간(화요일)
	HOS_TIME3S VARCHAR2(10),   	-- 진료시작시간(수요일)
	HOS_TIME4S VARCHAR2(10),   	-- 진료시작시간(목요일)
	HOS_TIME5S VARCHAR2(10),   	-- 진료시작시간(금요일)
	HOS_TIME6S VARCHAR2(10),   	-- 진료시작시간(토요일)
	HOS_TIME7S VARCHAR2(10),   	-- 진료시작시간(일요일)
	HOS_TIME8S VARCHAR2(10),   	-- 진료시작시간(공휴일)
	HOS_HPID VARCHAR2(20), 		-- 기관ID
	HOS_POSTCDN1 VARCHAR2(100),	-- 우편번호1
	HOS_POSTCDN2 VARCHAR2(100),	-- 우편번호2
	HOS_INFO VARCHAR2(500),		-- 기관설명상세
	HOS_LON VARCHAR2(30), 		-- 경도
	HOS_LAT VARCHAR2(30), 		-- 위도
	HOS_X VARCHAR2(30), 		-- X좌표
	HOS_Y VARCHAR2(30), 		-- Y좌표
	HOS_WEEKENDAT VARCHAR2(2), 	-- 주말진료여부
	 CONSTRAINT HOSPITAL_PK PRIMARY KEY (HOS_NUM)
);
CREATE SEQUENCE HOSPITAL_SEQ;

CREATE TABLE PHARMACY(
   PHA_NUM NUMBER NOT NULL,		-- 일련번호
   PHA_ADDR VARCHAR2(200),		-- 주소
   PHA_ETC VARCHAR2(1500),		-- 비고
   PHA_INFO VARCHAR2(500),		-- 기관설명상세
   PHA_MAPIMG VARCHAR2(200),	-- 간이약도
   PHA_NAME VARCHAR2(100),		-- 기관명
   PHA_TELL1 VARCHAR2(20),		-- 대표전화
   PHA_TIME1C VARCHAR2(10),		-- 진료종료시간(월요일)
   PHA_TIME2C VARCHAR2(10),		-- 진료종료시간(화요일)
   PHA_TIME3C VARCHAR2(10),		-- 진료종료시간(수요일)
   PHA_TIME4C VARCHAR2(10),		-- 진료종료시간(목요일)
   PHA_TIME5C VARCHAR2(10),		-- 진료종료시간(금요일)
   PHA_TIME6C VARCHAR2(10),		-- 진료종료시간(토요일)
   PHA_TIME7C VARCHAR2(10),		-- 진료종료시간(일요일)
   PHA_TIME8C VARCHAR2(10),		-- 진료종료시간(공휴일)
   PHA_TIME1S VARCHAR2(10),		-- 진료시작시간(월요일)
   PHA_TIME2S VARCHAR2(10),		-- 진료시작시간(화요일)
   PHA_TIME3S VARCHAR2(10),		-- 진료시작시간(수요일)
   PHA_TIME4S VARCHAR2(10),		-- 진료시작시간(목요일)
   PHA_TIME5S VARCHAR2(10),		-- 진료시작시간(금요일)
   PHA_TIME6S VARCHAR2(10),		-- 진료시작시간(토요일)
   PHA_TIME7S VARCHAR2(10),		-- 진료시작시간(일요일)
   PHA_TIME8S VARCHAR2(10),		-- 진료시작시간(공휴일)
   PHA_HPID VARCHAR2(20),		-- 기관ID
   PHA_POSTCDN1 VARCHAR2(100),	-- 우편번호1
   PHA_POSTCDN2 VARCHAR2(100),	-- 우편번호2
   PHA_LON VARCHAR2(30),		-- 경도
   PHA_LAT VARCHAR2(30),		-- 위도
   PHA_X VARCHAR2(30),			-- X좌표
   PHA_Y VARCHAR2(30),			-- Y좌표
   PHA_WEEKENDAT VARCHAR2(2),	-- 주말진료여부
   CONSTRAINT PHARMACY_PK PRIMARY KEY (PHA_NUM)
);
CREATE SEQUENCE PHARMACY_SEQ;

CREATE TABLE NOTIFICATION(
	NOTI_NUM NUMBER NOT NULL,						-- 알림식별자
	MEM_NUM NUMBER NOT NULL,						-- 회원식별자
	NOTI_CATEGORY NUMBER NOT NULL,					-- 카테고리
	NOTI_MESSAGE VARCHAR2(300) NOT NULL,			-- 메시지
	NOTI_ISREAD NUMBER(1) DEFAULT 0 NOT NULL,		-- 읽음처리
	NOTI_READEDDATE DATE,							-- 읽은 날짜
	NOTI_RESDATE DATE,								-- 예약 날짜
	NOTI_CREATEDDATE DATE DEFAULT SYSDATE NOT NULL,	-- 생성 날짜
	NOTI_LINK VARCHAR2(100),						-- 관련 URL
	NOTI_TYPE VARCHAR2(20) DEFAULT 'PUSH' NOT NULL,	-- 타입
	NOTI_PRIORITY NUMBER(1) DEFAULT 0 NOT NULL,		-- 우선순위
	CONSTRAINT NOTIFICATION_PK PRIMARY KEY (NOTI_NUM),
	CONSTRAINT NOTIFICATION_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);
CREATE SEQUENCE NOTIFICATION_SEQ;


-- 상담 추가 --
CREATE TABLE CONSULTING(
	CON_NUM NUMBER NOT NULL,						-- 상담 식별자
	MEM_NUM NUMBER NOT NULL,						-- 회원 식별자
	CON_TYPE NUMBER NOT NULL,						-- 상담 게시글의 유형 (0:구분없음 1:만성질환 2:여성질환 3:소화기질환 4:영양제 5:정신건강 6:처방약 7:탈모 8:통증 9:여드름,피부염 10:임신,성고민
	CON_TITLE VARCHAR2(150) NOT NULL,				-- 상담 게시글 제목
	CON_CONTENT VARCHAR2(900) NOT NULL,				-- 상담 게시글 내용
	CON_RDATE DATE DEFAULT SYSDATE NOT NULL,		-- 상담 게시글 등록일
	CON_MDATE DATE,									-- 상담 게시글 수정일
	CONSTRAINT CONSULTING_PK PRIMARY KEY (CON_NUM),
	CONSTRAINT CONSULTING_FK FOREIGN KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);
CREATE SEQUENCE CONSULTING_SEQ;

CREATE TABLE CON_REPLY(
	CON_RE_NUM NUMBER NOT NULL,						-- 상담 답글 식별자
	CON_NUM NUMBER NOT NULL,						-- 상담 식별자
	DOC_NUM NUMBER NOT NULL,						-- 의사 식별자
	CON_RE_CONTENT VARCHAR2(900) NOT NULL,			-- 상담 답글 내용
	CON_RE_RDATE DATE DEFAULT SYSDATE NOT NULL,		-- 상담 답글 등록일
	CON_RE_MDATE DATE,								-- 상담 답글 수정일
	CON_RE_STATUS NUMBER(1) DEFAULT 0 NOT NULL,		-- 상담 답글 반응 여부(0:미채택 1: 만족 2: 불만족)
	CONSTRAINT CON_REPLY_PK PRIMARY KEY (CON_RE_NUM),
	CONSTRAINT CON_REPLY_FK1 FOREIGN KEY (CON_NUM) REFERENCES CONSULTING(CON_NUM),
	CONSTRAINT CON_REPLY_FK2 FOREIGN KEY (DOC_NUM) REFERENCES MEMBER(MEM_NUM)
);
CREATE SEQUENCE CON_REPLY_SEQ;


